# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    build_app(workspace: "Vite.xcworkspace", scheme: "Vite")
    upload_to_testflight
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :package do
    increment_build_number
    build_app(workspace: "Vite.xcworkspace", scheme: "Vite")
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :git do
# 3、git add .

git_add(path: ".")

#  git commit -m 'message'

dd = get_build_number

git_commit(path: ".", message: "Jenkins Version Bump"+ dd)

#  git push origin master

#push_to_git_remote

  end
end





